"""Report validation and export.

The application checks evidence identity and conservative structured claim
prerequisites. It cannot semantically verify arbitrary model-written prose or
prove malicious/benign intent. Reports therefore keep three things apart:

* observed facts   — generated by code from retrieved records;
* hypotheses       — model interpretations whose structured prerequisites passed;
* verification     — concrete checks an analyst can perform next;

plus a collection-coverage ledger stating what was queried, what failed or was
truncated, and what remains unknown. Model prose is kept only as a clearly
labelled, unverified narrative.
"""

from __future__ import annotations

import html
import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timedelta

from . import attack
from .evidence import EvidenceStore, host_context_injection, looks_like_injection
from .models import (
    Alert,
    AttackMapping,
    CollectionCoverage,
    CollectionRequirement,
    CoverageItem,
    Evidence,
    Finding,
    HostContext,
    Hypothesis,
    InvestigationReport,
    InvestigationTrace,
    ObservedFact,
    ProcessNode,
    RecommendedAction,
    ReportDraft,
    TimelineEntry,
    ValidationResult,
    Verdict,
    VerificationStep,
)

CLAIM_VALUES = set(attack.CLAIM_RULES)
FINAL_REPORT_FAILED = "final_report_failed:"
CANCELLED = "cancelled:"
CONTEXT = "context:"  # the model may not have seen the prompt it was sent (overflow)
GROUNDING_LIMITATION = (
    "Automated validation checks evidence references and structured claim prerequisites only. "
    "Retained model narrative, verdict, confidence and recommendations are assessments requiring analyst review. "
    "ATT&CK mappings are behavioral hypotheses, not proof of malicious intent or successful compromise."
)

# Indicators that contradict a benign conclusion for the alerted process tree.
_TREE_CONTRADICTIONS = {"office_parent", "external_destination", "user_writable_path", "masquerade_suspect",
                        "suspicious_script_content"}
# Indicators that contradict a benign conclusion anywhere on the alerted host.
_HOST_CONTRADICTIONS = {"lsass_target", "memory_dump_file", "run_key", "scheduled_task", "masquerade_suspect",
                        "defender_detection"}

CLAIM_VERIFICATION: dict[str, str] = {
    "execution": "Confirm the process launch in endpoint history and whether it was expected for this user/host.",
    "obfuscation": "Review the decoded command content and identify the author/source of the script.",
    "office_child_process": "Retrieve the Office document involved and inspect it in a sandbox; confirm how it arrived.",
    "network_connection": "Look up the destination (reputation, ownership, prior contact from this host) and proxy/firewall logs.",
    "credential_theft": "Check for the dump file on disk, its handling, and sign-ins by accounts that used this host; plan credential resets.",
    "persistence": "Inspect the scheduled task / Run value and the referenced binary (hash, signer, origin); confirm whether it is authorised.",
    "brute_force": "Review the full authentication log for the account and source; check lockouts and other targeted accounts.",
    "account_compromise": "Confirm with the account owner; review activity performed by the session after the successful logon.",
    "discovery": "Determine who ran the discovery commands and whether they match an administrative task.",
    "benign_administration": "Confirm with the endpoint-management owner that this job ran, and verify the parent binary's signature and path.",
    "security_product_detection": "Review the Defender detection details (threat, path, action, remediation status) in Windows Security and confirm the file's origin.",
    "suspicious_script": "Read the full script block in the PowerShell Operational log and determine what it downloaded, loaded or changed.",
}


@dataclass
class ReportInputs:
    host_contexts: list[HostContext] = field(default_factory=list)
    backend_caveats: list[str] = field(default_factory=list)
    visibility_gaps: list[str] = field(default_factory=list)
    visibility_notes: list[str] = field(default_factory=list)  # disclosed, not incompleteness
    cancelled: bool = False
    # Reasons the final assessment prompt did not show the model every retrieved
    # record in full (omitted, summarized, suspected overflow). Empty = full view.
    model_visibility_issues: list[str] | None = None
    # Deterministic host-level signal check around the alert:
    # ("clear" | "signals" | "unavailable", details). None = not performed.
    host_signal_check: tuple[str, list[str]] | None = None
    # Network activity must cover at least this many minutes on each side of the
    # alert for benign closure (clamped to the configured window).
    min_network_window_minutes: int = 15


def _same_process(a: Evidence, b: Evidence) -> bool:
    return bool(a.process_guid and b.process_guid and a.host.casefold() == b.host.casefold()
                and a.process_guid.casefold() == b.process_guid.casefold())


def _pkey(host: str, guid: str) -> tuple[str, str]:
    return host.casefold(), guid.casefold()


def process_tree_keys(items: list[Evidence], roots: list[Evidence]) -> set[tuple[str, str]]:
    """(host, process_guid) of the root processes and ALL their descendants.

    Built from retrieved records' parent links only (same host). A fixed-point
    closure over a set: cycles and self-parenting records cannot loop, and the
    number of passes is bounded by the number of records.
    """
    tree = {_pkey(r.host, r.process_guid) for r in roots if r.process_guid}
    links = [(_pkey(e.host, e.parent_process_guid), _pkey(e.host, e.process_guid))
             for e in items if e.process_guid and e.parent_process_guid]
    for _ in range(len(links) + 1):
        added = {child for parent, child in links if parent in tree and child not in tree}
        if not added:
            break
        tree |= added
    return tree


def _in_tree(e: Evidence, tree: set[tuple[str, str]]) -> bool:
    """Any record performed by a process in the alerted process tree (the
    alerted process or any descendant, on the same host)."""
    return bool(e.process_guid and _pkey(e.host, e.process_guid) in tree)


def benign_blockers(store: EvidenceStore, alert: Alert, inputs: "ReportInputs | None" = None) -> list[str]:
    """Reasons a benign verdict cannot be accepted. Empty list means it may stand."""
    reasons: list[str] = []
    triggers = [e for e in (store.get(t) for t in store.trigger_ids()) if e is not None]
    items = store.all()
    if not triggers:
        return ["the triggering event was not retrieved"]
    if not any("management_agent_parent" in e.indicators and any(_same_process(e, t) for t in triggers)
               for e in items):
        reasons.append("administrative context was not established for the alerted process itself")
    if attack.malicious_hypothesis_supported(items):
        reasons.append("correlated malicious prerequisites are present in retrieved evidence")
    tree_keys = process_tree_keys(items, triggers)
    tree = {i for e in items for i in e.indicators if _in_tree(e, tree_keys)}
    host = {i for e in items for i in e.indicators if e.host.casefold() == alert.host.casefold()}
    contradicting = sorted((tree & _TREE_CONTRADICTIONS) | (host & _HOST_CONTRADICTIONS))
    if contradicting:
        reasons.append(f"contradicting indicators in the alerted process tree or host: {', '.join(contradicting)}")
    if any(e.injection_suspected for e in items):
        reasons.append("retrieved telemetry contains instruction-like text that requires analyst review")
    if inputs is not None and any(host_context_injection(hc) for hc in inputs.host_contexts):
        reasons.append("asset/host context contains instruction-like text; the asset record cannot be relied on")
    if any(looks_like_injection(str(v)) for v in (alert.title, alert.user, alert.host) if v):
        reasons.append("alert fields contain instruction-like text that requires analyst review")
    return reasons


# --- collection requirements for benign closure -----------------------------

def _parse_ts(value: object) -> datetime | None:
    try:
        return datetime.fromisoformat(str(value))
    except ValueError:
        return None


def evaluate_requirements(trace: InvestigationTrace, store: EvidenceStore, alert: Alert,
                          inputs: ReportInputs) -> list[CollectionRequirement]:
    """Check, from resolved tool-call records, that the minimum collection for
    benign closure succeeded: the alerted process tree, host-wide network
    activity around the alert, trustworthy host context, and a model view of
    all retrieved evidence. Never inferred from model prose."""
    triggers = [e for e in (store.get(t) for t in store.trigger_ids()) if e is not None]
    trig = triggers[0] if triggers else None
    anchor = trig.timestamp if trig else alert.timestamp
    ok = [c for c in trace.tool_calls if c.status == "ok" and c.target]
    reqs: list[CollectionRequirement] = []

    # 1. Process tree of the alerted process (ancestry + all descendants).
    tree_calls = [c for c in ok if c.tool == "get_process_tree" and trig and trig.process_guid
                  and str(c.target.get("process_guid", "")).casefold() == trig.process_guid.casefold()
                  and str(c.target.get("host", "")).casefold() == trig.host.casefold()]
    good = [c for c in tree_calls if c.outcome == "complete"
            or (c.outcome == "partial" and c.partial_reason == "ancestry_outside_window")]
    if trig is None:
        reason = "the triggering event was not retrieved, so its process tree cannot be established"
    elif not trig.process_guid:
        reason = "the triggering event has no process identity; process ancestry cannot be established"
    elif good:
        reason = "process ancestry and descendants of the alerted process were reconstructed"
    elif tree_calls:
        reason = ("the process-tree query for the alerted process was "
                  + ", ".join(sorted({(c.partial_reason or c.outcome or '?').replace('_', ' ') for c in tree_calls}))
                  + "; relevant processes may be missing")
    else:
        reason = "the process tree of the alerted process was never successfully queried"
    reqs.append(CollectionRequirement(name="process_tree", satisfied=bool(good), reason=reason,
                                      call_ids=[c.call_id for c in (good or tree_calls)]))

    # 2. Host-wide network/DNS activity covering the alert time.
    need = timedelta(minutes=inputs.min_network_window_minutes)
    net_calls = [c for c in ok if c.tool == "get_network_activity"
                 and str(c.target.get("host", "")).casefold() == alert.host.casefold()]
    # Either every connection on the host, or every connection of every process
    # in the alerted tree (checked against the tree as it stands at report time,
    # so a tree expanded after the network query does not count as covered).
    tree_guids = {g for h, g in process_tree_keys(store.all(), triggers) if h == alert.host.casefold()}
    good = []
    for c in net_calls:
        start, end = _parse_ts(c.target.get("start")), _parse_ts(c.target.get("end"))
        if not (c.outcome in ("complete", "empty") and start and end
                and start <= anchor - need and end >= anchor + need):
            continue
        if c.target.get("scope") == "process_tree":
            covered = {str(g).casefold() for g in c.target.get("process_guids", [])}
            if trig and trig.process_guid and str(c.target.get("tree_root", "")).casefold() == \
                    trig.process_guid.casefold() and tree_guids and tree_guids <= covered:
                good.append(c)
        elif not c.target.get("process_guid"):
            good.append(c)
    if good:
        reason = ("network/DNS activity of the whole alerted process tree was retrieved completely"
                  if good[0].target.get("scope") == "process_tree"
                  else "host-wide network/DNS activity around the alert was retrieved completely")
    elif any(c.outcome == "truncated" for c in net_calls):
        reason = "network activity results were capped; connections may be missing"
    elif net_calls:
        reason = (f"network activity was not retrieved for the host or for every process in the alerted tree "
                  f"over ±{inputs.min_network_window_minutes} minutes around the alert")
    else:
        reason = "host network activity was never successfully queried"
    reqs.append(CollectionRequirement(name="network_activity", satisfied=bool(good), reason=reason,
                                      call_ids=[c.call_id for c in (good or net_calls)]))

    # 3. Host context for the alerted host, free of instruction-like text.
    hc_calls = [c for c in ok if c.tool == "get_host_context"
                and str(c.target.get("host", "")).casefold() == alert.host.casefold()]
    good = [c for c in hc_calls if c.result_count > 0 and not c.injection_suspected]
    if good:
        reason = "asset context for the alerted host was retrieved"
    elif any(c.injection_suspected for c in hc_calls):
        reason = "asset context contains instruction-like text and cannot be relied on"
    elif hc_calls:
        reason = "no asset context exists for the alerted host"
    else:
        reason = "asset context for the alerted host was never successfully retrieved"
    reqs.append(CollectionRequirement(name="host_context", satisfied=bool(good), reason=reason,
                                      call_ids=[c.call_id for c in (good or hc_calls)]))

    # 4. No other security signal on the alerted host around the alert, checked
    #    deterministically over the host's telemetry (not via capped model queries).
    check = inputs.host_signal_check
    if check is None:
        reqs.append(CollectionRequirement(name="host_signals", satisfied=False,
                                          reason="the host-level signal check was not performed"))
    else:
        state, details = check
        reason = {"clear": "no other security signals on the host around the alert",
                  "signals": "other security signals exist on the host around the alert: " + "; ".join(details),
                  "unavailable": "the host-level signal check was incomplete: " + "; ".join(details)}[state]
        reqs.append(CollectionRequirement(name="host_signals", satisfied=state == "clear", reason=reason,
                                          call_ids=["system-host-signals"]))

    # 5. The assessment was made with every retrieved record in view.
    issues = inputs.model_visibility_issues
    if issues is None:
        issues = ["no model assessment prompt was recorded"]
    reqs.append(CollectionRequirement(
        name="model_visibility", satisfied=not issues,
        reason="the assessment prompt showed every retrieved record in full" if not issues else "; ".join(issues)))
    return reqs


def validate_report(
    draft: ReportDraft,
    store: EvidenceStore,
    alert: Alert,
    trace: InvestigationTrace,
    process_tree: list[ProcessNode],
    model: str,
    backend: str,
    started_at: datetime,
    completed_at: datetime,
    inputs: ReportInputs | None = None,
) -> InvestigationReport:
    inputs = inputs or ReportInputs()
    vr = ValidationResult()
    valid_ids = store.ids()
    findings: list[Finding] = []
    all_cited: set[str] = set()
    technique_finding_ids: dict[str, set[str]] = {}
    technique_evidence: dict[str, set[str]] = {}

    vr.draft_verdict = draft.verdict
    vr.proposed_claims = list(dict.fromkeys(str(c) for df in draft.findings for c in df.claims))
    vr.proposed_attack_techniques = list(dict.fromkeys(t for df in draft.findings for t in df.attack_techniques))
    for idx, df in enumerate(draft.findings, 1):
        vr.draft_evidence_refs += len(df.evidence_ids)
        real_ids = list(dict.fromkeys(eid for eid in df.evidence_ids if eid in valid_ids))
        bogus = [eid for eid in df.evidence_ids if eid not in valid_ids]
        if bogus:
            vr.invalid_evidence_refs.extend(bogus)
            vr.issues.append(f"Finding '{df.title[:40]}' referenced non-existent evidence {bogus}; dropped those refs.")
        if not real_ids:
            vr.dropped_findings += 1
            vr.issues.append(f"Finding '{df.title[:40]}' dropped: no valid evidence references remained.")
            continue
        cited_ev = [e for e in (store.get(eid) for eid in real_ids) if e is not None]

        kept_claims = []
        for claim in dict.fromkeys(df.claims):
            if claim not in CLAIM_VALUES:
                vr.issues.append(f"Finding '{df.title[:40]}' had unknown claim '{claim}'; ignored.")
                vr.rejected_claims += 1
                continue
            ok, why = attack.claim_supported(claim, cited_ev)  # type: ignore[arg-type]
            if ok:
                kept_claims.append(claim)
            else:
                vr.rejected_claims += 1
                vr.issues.append(f"Finding '{df.title[:40]}': rejected claim ({why}).")
        rejected = [c for c in df.claims if c not in kept_claims]

        fid = f"F-{idx:03d}"
        # A rejected tag must not leave the very same allegation in prose.
        # Untagged findings also cannot bypass structured validation.
        observations_only = bool(rejected) or not kept_claims
        if observations_only:
            vr.issues.append(f"Finding '{df.title[:40]}': replaced unchecked narrative with retrieved observations.")
        description = ("Retrieved observations only; the proposed interpretation was not accepted.\n" +
                       "\n".join(f"{e.evidence_id}: {e.description}" for e in cited_ev))[:2000]
        findings.append(Finding(
            finding_id=fid,
            title="Retrieved evidence observations" if observations_only else df.title,
            description=description if observations_only else df.description,
            severity="informational" if observations_only else df.severity,
            evidence_ids=real_ids, claims=kept_claims,  # type: ignore[arg-type]
            rejected_claims=[str(c) for c in rejected],
        ))
        all_cited.update(real_ids)

        for tech in dict.fromkeys(df.attack_techniques):
            ok, why = attack.technique_supported(tech, cited_ev)  # type: ignore[arg-type]
            if ok:
                technique_finding_ids.setdefault(tech, set()).add(fid)
                technique_evidence.setdefault(tech, set()).update(real_ids)
            else:
                vr.dropped_attack_mappings.append(tech)
                vr.issues.append(f"Dropped ATT&CK {tech}: {why}.")

    attack_mappings: list[AttackMapping] = []
    for tech_id, f_ids in technique_finding_ids.items():
        tech = attack.CATALOG[tech_id]
        attack_mappings.append(AttackMapping(
            technique_id=tech_id, name=tech.name, tactic=tech.tactic,
            finding_ids=sorted(f_ids), evidence_ids=sorted(technique_evidence[tech_id]),
        ))
    attack_mappings.sort(key=lambda m: m.technique_id)

    coverage = build_coverage(trace, store, alert, inputs)
    requirements = evaluate_requirements(trace, store, alert, inputs)

    # Referencing one real event is not enough to justify a strong verdict.
    verdict: Verdict = draft.verdict
    confidence = draft.confidence
    supported_claims = {claim for f in findings for claim in f.claims}
    if not supported_claims and verdict != "insufficient_evidence":
        vr.verdict_adjusted_from = verdict
        verdict = "insufficient_evidence"
        confidence = min(confidence, 0.3)
        vr.issues.append("Verdict downgraded to insufficient_evidence: no supported structured claims remained.")
    elif verdict == "benign":
        blockers = benign_blockers(store, alert, inputs)
        if "benign_administration" not in supported_claims:
            blockers.insert(0, "no finding established administrative context")
        # Benign closure must be earned by collection that actually succeeded;
        # "nothing suspicious was found" means nothing when nothing was looked at.
        blockers.extend(f"required collection not met ({r.name.replace('_', ' ')}): {r.reason}"
                        for r in requirements if not r.satisfied)
        if blockers:
            vr.verdict_adjusted_from = verdict
            verdict = "insufficient_evidence"
            confidence = min(confidence, 0.3)
            vr.issues.append("Benign verdict withheld: " + "; ".join(blockers) + ".")
    elif verdict == "likely_malicious" and not attack.malicious_hypothesis_supported(
            [e for e in store.all() if e.evidence_id in all_cited]):
        vr.verdict_adjusted_from = verdict
        verdict = "suspicious"
        confidence = min(confidence, 0.6)
        vr.issues.append("Likely-malicious verdict reduced: cited observations lacked the required correlated corroboration.")

    vr.valid = not bool(vr.issues)

    coverage.requirements = requirements
    status, status_reasons = _status(trace, coverage, inputs)

    timeline = _build_timeline(store.all(), all_cited)
    recommended = [RecommendedAction(action=a.action, rationale=a.rationale, priority=a.priority)
                   for a in draft.recommended_actions]

    limitations = list(draft.limitations)
    limitations.append(GROUNDING_LIMITATION)
    if status != "completed":
        limitations.append("Evidence gathering was incomplete or encountered errors; see collection coverage.")
        if verdict == "benign":
            vr.verdict_adjusted_from = verdict
            verdict = "insufficient_evidence"
            vr.valid = False
            vr.issues.append("Benign verdict withheld because evidence gathering was incomplete.")
        confidence = min(confidence, 0.5 if verdict != "insufficient_evidence" else 0.3)
    if status == "cancelled":
        verdict, confidence = "insufficient_evidence", 0.0
    if not vr.valid:
        recommended = [RecommendedAction(
            action="Review the retrieved evidence and validation notes before deciding on a response",
            rationale="The proposed report contained unsupported or unchecked interpretations.", priority="medium")]
        confidence = min(confidence, 0.6)
    # Model prose is kept only when validation made no corrections, and even then
    # it is labelled unverified. It never becomes the report summary.
    narrative = draft.summary if vr.valid and status not in ("failed", "cancelled") else None

    facts = _observed_facts(store, all_cited)
    hypotheses = _hypotheses(findings, attack_mappings)
    steps = _verification_steps(findings, attack_mappings, coverage, verdict, store)
    summary = _summary(verdict, confidence, status, facts, hypotheses, coverage, vr.valid, status_reasons)

    return InvestigationReport(
        investigation_id=trace.investigation_id, status=status, alert=alert,
        verdict=verdict, confidence=confidence, summary=summary,
        findings=findings, evidence=store.all(), timeline=timeline, process_tree=process_tree,
        attack_techniques=attack_mappings, recommended_actions=recommended,
        limitations=limitations, validation=vr, trace=trace, model=model, backend=backend,
        started_at=started_at, completed_at=completed_at,
        observed_facts=facts, hypotheses=hypotheses, verification_steps=steps,
        model_narrative=narrative, coverage=coverage, host_context=list(inputs.host_contexts),
        model_output_repairs=sum(1 for x in trace.llm_exchanges if x.purpose == "repair"),
        status_reasons=status_reasons,
    )


# --- coverage / status ------------------------------------------------------

_TOOL_CATEGORIES = {
    "get_network_activity": ["network", "dns"],
    "get_process_tree": ["process"],
    "get_process_details": ["process-related (all)"],
    "get_related_events": ["all"],
    "get_host_context": ["asset context"],
    "get_event": ["trigger"],
    "get_logon_activity": ["authentication", "privilege"],
    "get_powershell_activity": ["script"],
    "get_defender_activity": ["detection"],
}


def build_coverage(trace: InvestigationTrace, store: EvidenceStore, alert: Alert,
                   inputs: ReportInputs) -> CollectionCoverage:
    cov = CollectionCoverage(backend_caveats=list(inputs.backend_caveats))
    hosts: set[str] = set()
    categories: set[str] = set()
    unknowns: list[str] = []
    ok_tools: set[str] = set()
    for c in trace.tool_calls:
        outcome = c.outcome or {"ok": "complete", "error": "failed", "rejected": "rejected",
                                "duplicate": "duplicate"}[c.status]
        cov.items.append(CoverageItem(call_id=c.call_id, tool=c.tool, initiator=c.initiator,
                                      scope=c.scope or c.tool, outcome=outcome,  # type: ignore[arg-type]
                                      result_count=c.result_count, error_kind=c.error_kind,
                                      detail=c.error if c.status != "ok" else None))
        if c.status in ("ok", "error"):
            cov.queried += 1
        if outcome == "failed":
            cov.failed += 1
        elif outcome == "truncated":
            cov.truncated += 1
        elif outcome == "partial":
            cov.partial += 1
        elif outcome == "rejected":
            cov.rejected += 1
        elif outcome == "duplicate":
            cov.duplicates += 1
        if c.status == "ok":
            ok_tools.add(c.tool)
            host = c.arguments.get("host") if isinstance(c.arguments, dict) else None
            hosts.add(str(host) if host else alert.host)
            cat = c.arguments.get("category") if isinstance(c.arguments, dict) else None
            categories.update([cat] if (c.tool == "search_events" and cat) else
                              ["all"] if c.tool == "search_events" else _TOOL_CATEGORIES.get(c.tool, []))
        unknowns.extend(c.gaps)
    for e in store.all():
        hosts.add(e.host)
    if cov.rejected:
        unknowns.append(f"{cov.rejected} model-proposed request(s) were rejected before execution; "
                        "the data they targeted was not collected.")
    if not ({"get_network_activity"} & ok_tools) and not categories & {"all", "network", "dns"}:
        unknowns.append("Network/DNS activity was not queried.")
    trig = [store.get(t) for t in store.trigger_ids()]
    if any(t and t.process_guid for t in trig) and "get_process_tree" not in ok_tools:
        unknowns.append("Process ancestry of the alerted process was not reconstructed.")
    if "get_host_context" not in ok_tools:
        unknowns.append("Asset/role context for the host was not retrieved.")
    unknowns.extend(inputs.visibility_gaps)
    unknowns.extend(inputs.visibility_notes)
    if any(e.raw_truncated for e in store.all()):
        unknowns.append("Some raw records exceeded the storage bound and are kept as a hashed preview "
                        "(raw_sha256 identifies the full record).")
    budget_errors = [e for e in trace.errors if e.startswith("budget:")]
    unknowns.extend(e.split(":", 1)[1].strip().capitalize() + "." for e in budget_errors)
    cov.unknowns = list(dict.fromkeys(u for u in unknowns if u))
    cov.hosts_queried = sorted(hosts)
    cov.categories_queried = sorted(categories)
    cov.complete = not (cov.failed or cov.truncated or inputs.visibility_gaps or budget_errors
                        or any(e.startswith(("seed:", "decide:", "collection:", CONTEXT)) for e in trace.errors))
    return cov


def _status(trace: InvestigationTrace, coverage: CollectionCoverage, inputs: ReportInputs) -> tuple[str, list[str]]:
    reasons: list[str] = []
    if inputs.cancelled or any(e.startswith(CANCELLED) for e in trace.errors):
        return "cancelled", ["The investigation was cancelled before completion."]
    if any(e.startswith(FINAL_REPORT_FAILED) for e in trace.errors):
        reasons.append("The model did not produce a valid report after bounded repair attempts.")
    if coverage.failed:
        kinds = sorted({i.error_kind or "unknown" for i in coverage.items if i.outcome == "failed"})
        reasons.append(f"{coverage.failed} collection request(s) failed ({', '.join(kinds)}).")
    # v0.3: a capped exploratory query is disclosed in the coverage ledger
    # (truncated count, known unknowns, verification steps) but no longer makes
    # the investigation "incomplete": on a real host every host-wide query is
    # capped. Required collection is judged by the benign requirements instead,
    # where a truncated query never counts.
    reasons.extend(inputs.visibility_gaps)
    for e in trace.errors:
        if e.startswith((FINAL_REPORT_FAILED, "collection:")):
            continue
        reasons.append(e.split(":", 1)[1].strip() if ":" in e and e.split(":", 1)[0].isidentifier() else e)
    reasons = list(dict.fromkeys(reasons))
    if any(e.startswith(FINAL_REPORT_FAILED) for e in trace.errors):
        return "failed", reasons
    return ("incomplete" if reasons else "completed"), reasons


# --- facts / hypotheses / verification -------------------------------------

def _observed_facts(store: EvidenceStore, cited: set[str]) -> list[ObservedFact]:
    chosen = [e for e in store.all() if e.evidence_id in cited or e.evidence_id in store.trigger_ids()]
    chosen.sort(key=lambda e: (e.timestamp, e.evidence_id))
    facts = []
    for e in chosen:
        prefix = "Triggering event. " if e.evidence_id in store.trigger_ids() else ""
        facts.append(ObservedFact(evidence_id=e.evidence_id, timestamp=e.timestamp, host=e.host,
                                  statement=prefix + e.description, source_ref=e.source_ref))
    return facts


def _hypotheses(findings: list[Finding], mappings: list[AttackMapping]) -> list[Hypothesis]:
    out: list[Hypothesis] = []
    for f in findings:
        for claim in f.claims:
            out.append(Hypothesis(hypothesis_id=f"H-{len(out) + 1:03d}", kind="claim", label=claim,
                                  basis=f"Prerequisite met: {attack.CLAIM_RULES[claim][1]}",
                                  finding_ids=[f.finding_id], evidence_ids=f.evidence_ids))
    for m in mappings:
        out.append(Hypothesis(hypothesis_id=f"H-{len(out) + 1:03d}", kind="attack_technique",
                              label=f"{m.technique_id} {m.name}",
                              basis=f"Prerequisite met: {attack.CATALOG[m.technique_id].requirement}",
                              finding_ids=m.finding_ids, evidence_ids=m.evidence_ids))
    return out


def _verification_steps(findings: list[Finding], mappings: list[AttackMapping], cov: CollectionCoverage,
                        verdict: str, store: EvidenceStore) -> list[VerificationStep]:
    steps: list[VerificationStep] = []

    def add(step: str, reason: str, related: list[str]) -> None:
        if all(s.step != step for s in steps):
            steps.append(VerificationStep(step=step, reason=reason, related=related))

    for f in findings:
        for claim in f.claims:
            if claim in CLAIM_VERIFICATION:
                add(CLAIM_VERIFICATION[claim], f"Hypothesis '{claim}' is based on structured prerequisites, "
                    "not confirmed intent.", [f.finding_id, *f.evidence_ids])
    for item in cov.items:
        if item.outcome == "failed":
            add(f"Re-run or query manually: {item.scope}.", f"Collection failed ({item.error_kind}).", [item.call_id])
        elif item.outcome == "truncated":
            add(f"Retrieve the full result set for: {item.scope}.", "Results were capped.", [item.call_id])
    if any("parent of" in u and "not in the queried" in u for u in cov.unknowns):
        add("Retrieve the parent process record from the endpoint or a longer SIEM window.",
            "Earlier ancestry is unknown.", [])
    flagged = [e.evidence_id for e in store.all() if e.injection_suspected]
    if flagged:
        add("Review the flagged records directly in the source system; do not rely on model summaries of them.",
            "Telemetry contains instruction-like text.", flagged)
    if any("rule-matched" in c for c in cov.backend_caveats):
        add("Enable Wazuh archives (logall_json) and point SOCI_WAZUH_EVENTS_INDEX at the archives index.",
            "Only alert-generating events were searchable.", [])
    if verdict == "insufficient_evidence":
        add("Collect the missing telemetry listed under collection coverage and re-run the investigation.",
            "The available evidence did not support a determination.", [])
    return steps[:20]


def _summary(verdict, confidence, status, facts, hypotheses, cov: CollectionCoverage, valid, reasons) -> str:
    parts = [f"Assessment: {verdict.replace('_', ' ')} (model confidence {confidence:.2f}, uncalibrated). "
             f"Status: {status}."]
    parts.append(f"{len(facts)} observed fact(s) are cited; {len(hypotheses)} hypothesis(es) met structured "
                 "prerequisites (intent is not verified).")
    parts.append(f"Coverage: {cov.queried} quer{'y' if cov.queried == 1 else 'ies'}, {cov.failed} failed, "
                 f"{cov.truncated} truncated, {cov.partial} partial; {len(cov.unknowns)} known unknown(s).")
    if not valid:
        parts.append("Automated checks revised the model draft; the original output remains in the audit trace.")
    if reasons:
        parts.append("Status reasons: " + " ".join(reasons[:3]))
    return " ".join(parts)


def _build_timeline(evidence: list[Evidence], cited: set[str]) -> list[TimelineEntry]:
    entries = [TimelineEntry(timestamp=e.timestamp, evidence_id=e.evidence_id, host=e.host,
                             description=e.description, cited=e.evidence_id in cited)
               for e in evidence]
    entries.sort(key=lambda t: (t.timestamp, t.evidence_id))
    return entries


# --- exports ----------------------------------------------------------------


def report_to_json(report: InvestigationReport) -> str:
    return json.dumps(report.model_dump(mode="json"), indent=2)


def _markdown_text(value: str) -> str:
    """Render telemetry/model strings as inert text, never active Markdown or HTML."""
    # Escape only &, <, > as entities (quote=False): quote entities such as &#x27;
    # would be broken by the backslash-escaping of '#' below.
    text = html.escape(str(value), quote=False)
    text = re.sub(r"([\\`*_{}\[\]()#+\-.!|=~<>])", r"\\\1", text)
    # Collapse line structure so prose cannot form headings, rules or code blocks.
    return re.sub(r"\s*\n\s*", " / ", text).strip()


def report_to_markdown(report: InvestigationReport) -> str:
    r = report
    md = _markdown_text
    L: list[str] = []
    L.append(f"# Investigation {md(r.investigation_id)}")
    L.append("")
    L.append(f"> **{md(r.notice)}**")
    L.append("")
    L.append(f"- **Alert:** {md(r.alert.alert_id)} — {md(r.alert.title)}")
    L.append(f"- **Host:** {md(r.alert.host)}")
    L.append(f"- **Verdict:** `{r.verdict}`  |  **Model confidence (uncalibrated):** {r.confidence:.2f}")
    L.append(f"- **Model:** {md(r.model)}  |  **Backend:** {md(r.backend)}  |  **Status:** {r.status}")
    L.append(f"- **Started:** {r.started_at.isoformat()}  |  **Completed:** {r.completed_at.isoformat()}")
    L.append("")
    L.append("## Summary (application-generated)")
    L.append("")
    L.append(md(r.summary))
    L.append("")
    if r.status_reasons:
        L.append("## Why the status is not 'completed'" if r.status != "completed" else "## Status notes")
        L.append("")
        L.extend(f"- {md(x)}" for x in r.status_reasons)
        L.append("")
    L.append("## Observed facts (from retrieved records)")
    L.append("")
    if not r.observed_facts:
        L.append("- None cited.")
    for fct in r.observed_facts:
        L.append(f"- `{fct.timestamp.isoformat()}` {fct.evidence_id} — {md(fct.statement)} (ref {md(fct.source_ref)})")
    L.append("")
    L.append("## Hypotheses (prerequisites checked; intent not verified)")
    L.append("")
    if not r.hypotheses:
        L.append("- None met structured prerequisites.")
    for h in r.hypotheses:
        L.append(f"- {h.hypothesis_id} [{h.kind}] {md(h.label)} — {md(h.basis)}; evidence {', '.join(h.evidence_ids)}")
    L.append("")
    L.append("## Verification steps")
    L.append("")
    if not r.verification_steps:
        L.append("- None generated.")
    for v in r.verification_steps:
        L.append(f"- {md(v.step)} _({md(v.reason)})_")
    L.append("")
    L.append("## Model narrative (unverified)")
    L.append("")
    L.append(md(r.model_narrative) if r.model_narrative else
             "_Not shown: automated checks revised the draft or no assessment was produced. "
             "The raw model output is in the audit trace._")
    L.append("")
    c = r.coverage
    L.append("## Collection coverage")
    L.append("")
    L.append(f"- Queries: {c.queried} · failed {c.failed} · truncated {c.truncated} · partial {c.partial} · "
             f"rejected {c.rejected} · duplicates {c.duplicates} · complete: {'yes' if c.complete else 'no'}")
    L.append(f"- Hosts: {md(', '.join(c.hosts_queried) or 'none')} · Categories: {md(', '.join(c.categories_queried) or 'none')}")
    for item in c.items:
        extra = f" — {md(item.error_kind or '')} {md(item.detail or '')}".rstrip() if item.outcome in ("failed", "rejected") else ""
        L.append(f"  - {item.call_id} {md(item.tool)} [{item.outcome}] {md(item.scope)} ({item.result_count}){extra}")
    if c.requirements:
        L.append("- Required for benign closure:")
        L.extend(f"  - {'met' if q.satisfied else 'NOT met'}: {md(q.name.replace('_', ' '))} — {md(q.reason)}"
                 for q in c.requirements)
    if c.backend_caveats:
        L.append("- Backend caveats:")
        L.extend(f"  - {md(x)}" for x in c.backend_caveats)
    if c.unknowns:
        L.append("- Known unknowns:")
        L.extend(f"  - {md(x)}" for x in c.unknowns)
    L.append("")
    if r.host_context:
        L.append("## Host context (untrusted asset metadata)")
        L.append("")
        for hc in r.host_context:
            L.append("- " + md("; ".join(f"{k}: {v}" for k, v in hc.model_dump(exclude_none=True).items())))
        L.append("")
    if r.findings:
        L.append("## Findings")
        L.append("")
        for f in r.findings:
            L.append(f"### {f.finding_id}: {md(f.title)}  _(severity: {f.severity})_")
            L.append("")
            L.append(md(f.description))
            L.append("")
            L.append(f"- Evidence: {', '.join(f.evidence_ids)}")
            if f.claims:
                L.append(f"- Claims: {', '.join(f.claims)}")
            L.append("")
    if r.attack_techniques:
        L.append("## MITRE ATT&CK (hypotheses)")
        L.append("")
        L.append("| Technique | Name | Tactic | Findings | Evidence |")
        L.append("| --- | --- | --- | --- | --- |")
        for mapping in r.attack_techniques:
            L.append(f"| {mapping.technique_id} | {md(mapping.name)} | {md(mapping.tactic)} | "
                     f"{', '.join(mapping.finding_ids)} | {', '.join(mapping.evidence_ids)} |")
        L.append("")
    if r.timeline:
        L.append("## Timeline")
        L.append("")
        for t in r.timeline:
            mark = "★" if t.cited else " "
            L.append(f"- `{t.timestamp.isoformat()}` [{mark}] {t.evidence_id} — {md(t.description)}")
        L.append("")
    L.append("## Evidence")
    L.append("")
    for e in r.evidence:
        flag = " ⚠ possible-injection" if e.injection_suspected else ""
        prov = f"sha256 {e.raw_sha256[:16]}…" if e.raw_sha256 else "no hash"
        if e.raw_truncated:
            prov += ", raw truncated"
        if e.truncated_fields:
            prov += f", clipped fields: {', '.join(e.truncated_fields)}"
        L.append(f"- **{e.evidence_id}** ({e.category}, {md(e.source)}, ref {md(e.source_ref)}; {prov}){flag}: "
                 f"{md(e.description)}")
    L.append("")
    if r.recommended_actions:
        L.append("## Recommended Actions (not executed)")
        L.append("")
        for a in r.recommended_actions:
            L.append(f"- _[{a.priority}]_ {md(a.action)} — {md(a.rationale)}")
        L.append("")
    if r.limitations:
        L.append("## Limitations")
        L.append("")
        for lim in r.limitations:
            L.append(f"- {md(lim)}")
        L.append("")
    v = r.validation
    if v.draft_verdict is not None:
        L.append("## Model draft vs. accepted")
        L.append("")
        accepted_claims = sorted({c for f in r.findings for c in f.claims})
        accepted_tech = sorted(m.technique_id for m in r.attack_techniques)
        L.append(f"- Draft verdict: `{v.draft_verdict}` → accepted verdict: `{r.verdict}`")
        L.append(f"- Claims proposed: {md(', '.join(v.proposed_claims) or 'none')} · accepted: "
                 f"{md(', '.join(accepted_claims) or 'none')}")
        L.append(f"- ATT&CK proposed: {md(', '.join(v.proposed_attack_techniques) or 'none')} · accepted: "
                 f"{md(', '.join(accepted_tech) or 'none')}")
        L.append("- Claims describe observed behavior only; intent and outcome are not verified.")
        L.append("")
    if r.revision is not None:
        rv = r.revision
        L.append("## Validation-feedback revision")
        L.append("")
        L.append(f"- Performed: {'yes' if rv.performed else 'no'} · changed the assessment: "
                 f"{'yes' if rv.changed else 'no'}")
        L.append(f"- First draft: verdict `{rv.first_draft_verdict}` → validated `{rv.first_validated_verdict}`; "
                 f"accepted claims {md(', '.join(rv.first_accepted_claims) or 'none')}; rejected "
                 f"{md(', '.join(rv.first_rejected_claims) or 'none')}")
        if rv.performed:
            L.append(f"- Revised draft: verdict `{rv.revised_draft_verdict}`; accepted claims "
                     f"{md(', '.join(rv.final_accepted_claims) or 'none')}")
        if rv.note:
            L.append(f"- {md(rv.note)}")
        L.append("")
    if not r.validation.valid or r.validation.issues:
        L.append("## Validation Notes")
        L.append("")
        for issue in r.validation.issues:
            L.append(f"- {md(issue)}")
        L.append("")
    clipped = [x for x in r.trace.llm_exchanges if x.clipped or x.evidence_omitted]
    L.append("## Audit disclosure")
    L.append("")
    L.append(f"- Model exchanges: {len(r.trace.llm_exchanges)}; repair attempts: {r.model_output_repairs}; "
             f"exchanges with clipped audit copies or omitted evidence: {len(clipped)}.")
    return "\n".join(L)
